require("janders223.treesitter")
require("janders223.lsp")
require("janders223.completion")
require("janders223.trouble")
require("janders223.noice")
require("janders223.notify")
require("janders223.lualine")
require("janders223.autopairs")
