vim.keymap.set('n', '<leader>gt', ':TroubleToggle<CR>')
vim.keymap.set('i', 'jk', '<esc>')
vim.keymap.set('n', '<leader>w', ':w<CR>')
vim.keymap.set('n', '<leader>wq', ':wqa<CR>')
vim.keymap.set('n', '<leader><leader>', ':nohl<CR>')
vim.keymap.set('n', '<leader>q', ':q<CR>')
vim.keymap.set('n', '<leader>qq', ':qa<CR>')
vim.keymap.set('n', '<leader>t', ':tabnew<CR>')
